### ISSUE TITLE
Allow drush sql-sync from production during post-rollout tasks

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#1267]
With Lagoon 1.0.0 and RBAC all post-rollout tasks and also all remote connections tasks are running under a user that has `guest` Role. This `guest` does not have permissions to use the remote shell and therefore running `drush sql-sync` within a post-rollout task or inside a remote shell connection will fail.

This problem also existed for Lagoon Tasks, but we solved this with injecting a maintainer token into the Task Pod: https://github.com/amazeeio/lagoon/issues/1229

For problem here there are multiple possible solutions:
1. give the remote shell connection a role that can use remote shell connections (like `maintainer` or create a new role all together). While this solves the underlining problem and has been tested already it would allow a user with no access to the production environment allow to elevate it's own priviledges with connecting into the development environment and "steal" the SSH key of the default user which has this additional. Therefore allowing developers without production environment access to access such enviornment.
2. Abandoning running of `drush sql-sync` during a post-rollout task all together and instead write a small bash script which creates a lagoon task for running `drush-sql sync` inside that task and then within the bash script to wait until that lagoon task has been finished. This technically would work but brings it's own challenges:
    1. it would mean that all projects currently directly using `drush sql-sync` inside post-rollout will fail.
    2. there is currently no example for such a bash script that can create a Lagoon Task
    3. Debugging failures of the drush sql-sync will be much harder as the command runs within another pod and logs are a bit trickier to load.
    4. Lagoon Tasks require an environment to successfully be deployed. In some cases the environment we create the task in might not be fully deployed yet.

3. Abandoning running of `drush sql-sync` during a post-rollout task all together and allow to trigger Lagoon Tasks via `.lagoon.yml` post rollout tasks. The Post Rollout Tasks yaml scheme is already prepared to run other type of tasks than `run`. We could there directly do something like:
    ```
   post-rollout:
     - task:
         name: sync db from master to local
         type: drush_sql-sync
         source: @master
         destination: @self
    ```
    Which then automatically creates a Lagoon Task, waits until that lagoon task is done and continues with the deployment. While this is probably much easier to use than running a BashScript in Solution 2, there are still downsides:
    1. it would mean that all projects currently directly using `drush sql-sync` inside post-rollout will fail.
    2. many projects check first if the database exists on the current environment and only if it does not exist, then it runs the sync command, so we probably would need to provide something like:
        ```
        post-rollout:
          - task:
              name: sync db from master to local
              type: drush_sql-sync
              source: @master
              destination: @self
              only_if: tables=$(drush sqlq 'show tables;') && [ -z "$tables" ]
        ```
        which runs the task only if the defined script does not fail
4. during any remote shell connection we could inject the Lagoon JWT of the user that currently is connecting to the remote shell into the destination of the connection (like the 'cli' container). This would technically remove the need to inject an SSH key into the CLI container all together. There are only a couple of issues to solve:
    1. Admins accessing the CLI container directly via the OpenShift UI or via `oc rsh` would not have a JWT at all, as they are not connecting via the lagoon remote shell system and therefore no JWT token would be generated. (this probably speaks to the fact to keep the ssh key with the default-user).
    2. The Lagoon Build Process runs under the default-user and authenticates with this user against the Lagoon API. We would need to allow that user role to have permission to access the production environment.

I personally think Nr. 4 is the best solution we could do right now, as it makes the most sense to have the same JWT running inside a remote shell as the user that connects to it (basically mimiks the SSH Agent system).
