### ISSUE TITLE
possible to define variables for use in .lagoon.yml pre/post rollout tasks?

### ISSUE THREAD

**Issue by tobybellwood** [uselagoon/lagoon#1487]
Having a variable available in .lagoon.yml that could be used in pre-rollout / post-rollout tasks would be a killer feature - it would avoid having to define variables permanently for environments - and the variable value would be committed to code alongside the commands

e.g.
```
tasks:
  variables:
    BACKUP_DIR: "/app/web/sites/default/files/private/backups"
  pre-rollout:
    - run:
        name: Snapshot the database and store
        command: |
          if [[ "$LAGOON_ENVIRONMENT_TYPE" = "production" ]]; then 
			drush sql:dump --root=/app --gzip --result-file="$BACKUP_DIR"/pre-deploy-dump.sql; 
		  fi
        service: cli
        shell: bash
  post-rollout:
    - run:
        name: Preserve the backup from this successful post-rollout
        command: |
          BACKUP="$BACKUP_DIR"/pre-deploy-dump.sql.gz
          if -f "$BACKUP"; then mv "$BACKUP" "$BACKUP_DIR"/last-good.tar.gz; fi
        service: cli

```

Gitlab has a nice implementation:
https://docs.gitlab.com/ee/ci/variables/#via-gitlab-ciyml
