### ISSUE TITLE
Allow pre and post rollout tasks to be executed conditionally 

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1648]
**Describe the feature**

At present, both `pre` and `post` rollout tasks will always execute ([docs link](https://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/#pre-rollout-tasks-pre_rolloutirun)).

It would be handy to allow a `depends` condition on the task, so that it only runs when it should.

This will allow you to craft environment variables that alter the way a release works. For example, you could have a `hotfix` release type (to which runs no cache clears, or database updates), and a `full` release type (which runs the full show).

**Current behavior**

```
tasks:
  post-rollout:
    - 
      run:
        name: Database Updates
        command: drush --uri=/app updatedb
        service: cli
```

**Proposed behavor**

Some additional keys in the `.lagoon.yml` file, e.g.:

```
tasks:
  post-rollout:
    - 
      depends:
        env: RELEASE_TYPE=FULL
      run:
        name: Database Updates
        command: drush --uri=/app updatedb
        service: cli
```

**Existing workarounds**

You can just alter the script, to include more `if` logic, but this makes the entire command more unreadable

```
tasks:
  post-rollout:
    - 
      run:
        name: Database Updates
        command: if [ "$RELEASE_TYPE" = "FULL" ] ; then drush --uri=/app updatedb ; fi
        service: cli
```

**Comment by klonos** [comment]
This feature would help reduce a lot of overhead in the GovCMS Service Desk...

As it is currently, post-rollout tasks in the `.lagoon.yml` file of GovCMS8 projects include a config import task, which is disabled by default. This is in order to prevent accidental config reversal of changes made directly to the actual site/environment via the Drupal admin UI (agencies that do not have a dev team/partner, hence do not export config and commit it to their repo).

PaaS customers can self-serve, but the .lagoon.yml file is locked for GovCMS SaaS customers. This leads to their dev team/partners constantly raising support tickets to have the automatic config import task enabled on their behalf while they do ad-hoc work for the agency, and then re-disable it once the job is done. The overhead caused by this is even greater when there are multiple branches for which the request to enable/disable the config task is made.

If there was a way to read a variable which the customer could specify in an unlocked file, and then have the config task conditionally run based on that, then that would save us so much time from having to deal with such trivial requests.

**Comment by AntoineOsanz** [comment]
Hi @tobybellwood , can you advise where this might stand on the Lagoon roadmap?

**Comment by tobybellwood** [comment]
A deeper look into lagoon.yml and tasks more generally is scheduled post-Lagoon 2.0.

The work around that GovCMS has in place (i.e. the tasks calling a script that asseses the conditional itself) is ultimately more configurable, but I appreciate the simplicity of including the option in lagoon.yml

**Comment by shreddedbacon** [comment]
Just had a chat with someone about additional conditionals for post-rollout tasks, and that it could be nice be able to specify if tasks could run based on whether the build completes or fails, or either.

Something like this maybe
```
tasks:
  post-rollout:
    - run:
        name: Database Updates
        command: drush --uri=/app updatedb
        service: cli
        on-failure: true|false
        on-completion: true|false
```
