### ISSUE TITLE
Possibility to define tasks in .lagoon.yml

### ISSUE THREAD

**Issue by dasrecht** [uselagoon/lagoon#1826]
During a discussion around #1825 (overwriting in which container tasks should run), we ended up discussing that it would be powerful to define custom tasks in the .lagoon.yml which then would show up in the dashboard for users to execute.

Possible use-cases could be emptying a `redis` cache or custom tasks in node.js applications but it's not limited.

We could extend the `tasks` section in the `.lagoon.yml` with a section `custom-tasks` e.g.

```
tasks:
  custom:
    - task:
        name: Redis - Flush All
         command: redis-cli FLUSHALL
         service: mycustomrediscontainer
```
