### ISSUE TITLE
Create route option to force www redirect

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1947]
The idea here is to allow another `.lagoon.yml` option to be attached to a given domain, that will force all requests to be immediate HTTP 301 redirects to the same URI but the HTTP host will have `www.` prepended.

e.g. the `.lagoon.yml`:

```
environments:
  master:
    routes:
      - nginx:
        - example.com
            tls-acme: 'true'
            www-redirect: 'true'
        - www.example.com:
            tls-acme: 'true'
```

## Workaround

Currently the best way to do this, is to amend the Nginx image to add in a redirect, this however requires a lot of base knowledge to execute.
