### ISSUE TITLE
Create route option to enable WAF

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#1948]
The idea here is to allow another `.lagoon.yml` option to be attached to a given domain, that will enable ModSecurity with a given profile.

e.g. the `.lagoon.yml`:

```
environments:
  master:
    routes:
      - nginx:
        - www.example.com:
            tls-acme: 'true'
            waf: 'drupal'
```

This would also allow Lagoon to be aware of who is running a WAF, and thus can influence billing.
