### ISSUE TITLE
allow specifying a list of prefixes for auto-generated routes

### ISSUE THREAD

**Issue by twardnw** [uselagoon/lagoon#2004]
For situations where a customer project is utilizing domain-based language detection, it would be ideal if Lagoon could auto-generate routes given an array of prefixes.

In the .lagoon.yml we could specify:
```
routes:
  autogenerate:
    prefixes:
      - de
      - it
      - en
      - www
```
then during the build process this list be iterated, creating an ingress/route for each prefix, on each service which receives auto-generated routes.
