### ISSUE TITLE
Invalid YAML in pvc annotations

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#2551]
# Describe the bug

The YAML generated by Helm is invalid for `pvc` in the `nginx-php-persistent` template

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-php
  labels:
    helm.sh/chart: nginx-php-persistent-0.1.0
    app.kubernetes.io/name: nginx-php-persistent
    app.kubernetes.io/instance: nginx-php
    app.kubernetes.io/managed-by: Helm
    lagoon.sh/service: nginx-php
    lagoon.sh/service-type: nginx-php-persistent
    lagoon.sh/project: REDACTED
    lagoon.sh/environment: production
    lagoon.sh/environmentType: production
    lagoon.sh/buildType: branch
  annotations:
    lagoon.sh/version: "21.2.2"
    lagoon.sh/branch: "production"
  annotations:
    k8up.syn.tools/backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bulk
  resources:
    requests:
      storage: "20Gi"
```

Notice the double `annotations` key.

## To Reproduce

Do a deploy, notice the the YAML is not valid.

## Expected behavior

Valid YAML being generated by Helm

**Comment by Schnitzel** [comment]
what's not valid on it? http://www.yamllint.com/ and https://codebeautify.org/yaml-validator both say it's valid yaml.

creating an object with it works:

```
❯ cat <<EOF | kubectl apply -f -
pipe heredoc> apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-php
  labels:
    helm.sh/chart: nginx-php-persistent-0.1.0
    app.kubernetes.io/name: nginx-php-persistent
    app.kubernetes.io/instance: nginx-php
    app.kubernetes.io/managed-by: Helm
    lagoon.sh/service: nginx-php
    lagoon.sh/service-type: nginx-php-persistent
    lagoon.sh/project: REDACTED
    lagoon.sh/environment: production
    lagoon.sh/environmentType: production
    lagoon.sh/buildType: branch
  annotations:
    lagoon.sh/version: "21.2.2"
    lagoon.sh/branch: "production"
  annotations:
    k8up.syn.tools/backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bulk
  resources:
    requests:
      storage: "20Gi"
EOF
persistentvolumeclaim/nginx-php created```

**Comment by seanhamlin** [comment]
The [linter](http://www.yamllint.com/) you mentioned, says it is valid, but it also has changed the format of the result

```yaml
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  annotations: 
    k8up.syn.tools/backup: "true"
  labels: 
    app.kubernetes.io/instance: nginx-php
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nginx-php-persistent
    helm.sh/chart: nginx-php-persistent-0.1.0
    lagoon.sh/buildType: branch
    lagoon.sh/environment: production
    lagoon.sh/environmentType: production
    lagoon.sh/project: REDACTED
    lagoon.sh/service: nginx-php
    lagoon.sh/service-type: nginx-php-persistent
  name: nginx-php
spec: 
  accessModes: 
    - ReadWriteMany
  resources: 
    requests: 
      storage: 20Gi
  storageClassName: bulk
```

Notice the single `annotations` key now? Perhaps it is ignoring one of the keys.

from the spec https://yaml.org/spec/1.2/spec.html

> JSON's RFC4627 requires that mappings keys merely “SHOULD” be unique, while YAML insists they “MUST” be. Technically, YAML therefore complies with the JSON spec, choosing to treat duplicates as an error. In practice, since JSON is silent on the semantics of such duplicates, the only portable JSON files are those with unique keys, which are therefore valid YAML files.

Also https://yaml.org/spec/1.2/spec.html#id2764044

> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique

The fix seems simply enough too.
