### ISSUE TITLE
Active / Standby switch does not update LAGOON_ROUTE variable

### ISSUE THREAD

**Issue by nicksantamaria** [uselagoon/lagoon#3248]
# Describe the bug

When using the Active/Standby deployment feature, there is an issue relating to the LAGOON_ROUTE variable.

After the active/standby switch is complete, the new `active` environment continues to use the `standby` `LAGOON_ROUTE` variable. This seems innocuous, but has some downstream impacts which do cause problems.

For example, in a Drupal site, the LAGOON_ROUTE variable is used to build the URL of content indexed in elasticsearch. This issue causes results from elasticsearch to show the standby URL.

## To Reproduce

Assume the following configuration in a project's `.lagoon.yml` 

```yaml
environments:
  prod-a:
    ...
  prod-b:
    ....
production_routes:
  active:
    routes:
      - nginx-php:
        - "www.foo.com"
  standby:
    routes:
      - nginx-php:
        - "standby.foo.com"
```

- Assume `prod-a` is set as the `active` environment.
- Assume `prod-b` is set as the `standby` environment.
- Deploy the `prod-b` environment. 
- Look at the `LAGOON_ROUTE` value in the configmap, it should be `standby.foo.com`.
- Run the active/standby switch.
- Look at the `LAGOON_ROUTE` value in the configmap, it should be `www.foo.com`, but it is actually still using the old value.

## Expected behavior

After running the steps above, the `LAGOON_ROUTE` value in the `prod-b` configmap should be `www.foo.com`.
