### ISSUE TITLE
Support Shared S3 Bucket for K8up Backups

### ISSUE THREAD

**Issue by anothertobi** [uselagoon/lagoon#3444]
## Context

AWS has hard limit on the number of S3 buckets one can create within an account (1000). Lagoon sets the backup bucket name on a project level (`baas-${project}`) and offloads the credentials and bucket creation to K8up on the Kubernetes cluster. With this approach a cluster can not contain over 1000 projects without configuring custom backup locations on a project level.

## Idea

K8up uses Restic under the hood which supports multiple Restic repositories within the same S3 bucket using different paths. This can be leveraged by introducing an (opt-in) option to configure a shared S3 bucket on a Lagoon Remote (~K8s cluster) level.

### Rough Example
Old:
```
# S3 bucket name supplied to K8up
baas-project-a
baas-project-c
```

New:
```
# Config for Lagoon Remote
baasSharedBucketName: cluter-x-shared-bucket

# S3 bucket name supplied to K8up
cluter-x-shared-bucket/baas-project-a
cluter-x-shared-bucket/baas-project-c
```

```
---
apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
spec:
  backend:
    s3:
      bucket: cluter-x-shared-bucket/baas-project-a
[...]
```

### Additional Information

AFAIK Lagoon Core needs to the know the full bucket name to start a restore. Otherwise it might be possible to implement this only within Lagoon Remote (https://github.com/uselagoon/build-deploy-tool)
