### ISSUE TITLE
Path based routing

### ISSUE THREAD

**Issue by seanhamlin** [uselagoon/lagoon#3642]
In order to work around a [Next.js core issue](https://github.com/vercel/next.js/issues/39294) in which having two application pods causes 'preview mode' to only work 50% of the time, it would be great to have more flexibility when in comes to path based routing to services.

In this particular use case, we are thinking:

* `/api/preview` -> service `preview` - 1 replica only
* `/` -> service `node` - 2+ replicas (HPA in place)

This seems like the most supportable option for running Next.js with Lagoon for now.

**Comment by shreddedbacon** [comment]
I think this is doable, we'd need to make sure that it is something we can support long term though. And is also somewhat guardrailed, will chat amongst the team with some possible implementation methods

**Comment by shreddedbacon** [comment]
Might need to move this to the build-deplo-tool repo, but will leave it here for now

**Comment by dwoods** [comment]
I'm not sure if this is the same thing, but what we'd like to do is have routes in different projects/environments share the same hostname with a different path.

So for example, in project `site-1', we would have the following route:

```yaml
project: site-1

environments:
  main:
    routes:
      - nginx:
          - "www.example.com/site-1":
```

And in project `site-2`:

```yaml
project: site-2

environments:
  main:
    routes:
      - nginx:
          - "www.example.com/site-2":
```

Ideally this would result in the hostname and path being split out, and creating the Ingresses appropriately.

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www.example.com--site-1
  namespace: site-1-main
  annotations:
    standard: stuff
  labels:
    lagoon.sh/autogenerated: 'false'
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/primaryIngress: 'true'
    lagoon.sh/project: site-1
    lagoon.sh/service-type: custom-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.example.com
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  name: http
            path: /site-1
            pathType: Prefix
  tls:
    - hosts:
        - www.example.com
      secretName: www.example.com-tls
```

And the other:

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: www.example.com--site-2
  namespace: site-2-main
  annotations:
    standard: stuff
  labels:
    lagoon.sh/autogenerated: 'false'
    lagoon.sh/buildType: branch
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/primaryIngress: 'true'
    lagoon.sh/project: site-2
    lagoon.sh/service-type: custom-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: www.example.com
      http:
        paths:
          - backend:
              service:
                name: nginx
                port:
                  name: http
            path: /site-2
            pathType: Prefix
  tls:
    - hosts:
        - www.example.com
      secretName: www.example.com-tls
```

I believe the standard ingress-nginx controller will [handle this](https://kubernetes.github.io/ingress-nginx/how-it-works/#building-the-nginx-model) and merge the definitions into the same server block.

In our case we're using the NGINX Plus ingress controller which requires an [additional annotation](https://github.com/nginxinc/kubernetes-ingress/tree/v3.4.2/examples/ingress-resources/mergeable-ingress-types) for this to work, but that's easy enough.

We're currently working around this by having another handler that proxies to the Ingresses (domain masking).  But this is clunky and the URLs of the routes in Lagoon don't accurately reflect the actual external URL.

Does this sound like the same feature?
