### ISSUE TITLE
Unable to increase size of persistent storage

### ISSUE THREAD

**Issue by kasperg** [uselagoon/lagoon#3889]
# Describe the bug

[The default value of a persistent storage volume is 5Gi but it can be configured with the `lagoon.persistent.size` label](https://docs.lagoon.sh/concepts-basics/docker-compose-yml/#supported-persistent-volume-flags).

We have not been able to change the size of a persistent storage volume once it has been deployed in an environment.

This is a bit surprising as we use the persistent storage for user uploaded files which is expected to increase over time.

## To Reproduce

1. Create a `docker-compose.yml` file for your Lagoon project with the following structure (abbreviated for clarity):

```yaml
services:
  cli:
    image: uselagoon/php-8.1-cli-drupal:latest
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent.name: nginx
      lagoon.persistent: /app/web/sites/default/files/

  nginx:
    image: uselagoon/nginx-drupal:latest
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/web/sites/default/files/

  php:
    image: uselagoon/php-8.3-fpm:latest
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.name: nginx
      lagoon.persistent: /app/web/sites/default/files/
```

2. SSH to the CLI container using the `lagoon` CLI
3. See the size of the mounted filesystem is 5Gi using `df -h` or the like
4. Add `lagoon.persistent.size: 10Gi` to `services.nginx.labels`
5. Deploy the changes
6. SSH to the CLI container and see the size of the mounted filesystem.

## Expected behavior

I expected one of the following in preferred order:

1. The size of the mounted filesystem to increase to 10Gi
2. The deployment to fail because the size cannot be increased. We also get an error if we decrease the size.
3. The documentation to state that persistent volumes cannot be increased

## Additional context

I wonder why this error occurs. As far as I can tell from the deployment log output the step *Applying Deployments* contains a manifest with the expected size:

```
# Source: nginx-php-persistent/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx
  labels:
    helm.sh/chart: nginx-php-persistent-0.1.0
    app.kubernetes.io/name: nginx-php-persistent
    app.kubernetes.io/instance: nginx
    app.kubernetes.io/managed-by: Helm
    lagoon.sh/service: nginx
    lagoon.sh/service-type: nginx-php-persistent
    lagoon.sh/project: aarhus
    lagoon.sh/environment: main
    lagoon.sh/environmentType: production
    lagoon.sh/buildType: branch
  annotations:
    lagoon.sh/version: "23.12.0"
    lagoon.sh/branch: "main"
    k8up.syn.tools/backup: "true"
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: bulk
  resources:
    requests:
      storage: "10Gi"
```
