### ISSUE TITLE
add polysite project and routes in .lagoon.yml

### ISSUE THREAD

**Issue by rtprio** [uselagoon/lagoon#482]
Trying to do a poly site all set to the same branch and running into the following limitations:

- can't add unique routes as every branch is master.
- can't set `&lagoon-project` in docker-compose as it changes depending on which of the subsites.

**Comment by Schnitzel** [comment]
```
project:
  polysite1:
    environments:
      master:
        routes:
          - nginx:
            - example.com
```
