### ISSUE TITLE
Replace oc-build-deploy-dind with helm

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#564]
Basically what the title says :)

We know that what is happening in here: https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh is very very similar to what Helm.sh already can do, therefore this issue is to come up with a POC on how this could work.

Some background for people of the Helm community how `build-deploy-docker-compose.sh` is actually called.

Looking at https://www.lucidchart.com/documents/view/a3cf0c4f-1bc1-438f-977d-4b26f235ceac#
a request comes in from the left and goes through multiple microservices within Lagoon. Lagoon will then create a new project (namespace) within OpenShift and trigger a BuildConfig within OpenShift (which is basically nothing else then just a Kubernets Job which creates a single Pod that has privileged permissions).
This Kubernetes Pod executes the Docker Image `oc-build-deploy-dind` with a couple of ENV variables injected, an example:

```
      env:
        - name: TYPE
          value: branch
        - name: GIT_REF
          value: fa09dbf4cb2da05d19b772e4516878e8d7631202
        - name: SAFE_BRANCH
          value: master
        - name: BRANCH
          value: master
        - name: SAFE_PROJECT
          value: drupal-example
        - name: PROJECT
          value: drupal-example
        - name: ENVIRONMENT_TYPE
          value: development
        - name: SOURCE_REPOSITORY
           value: git@github.com:amazeeio/drupal-example.git
```

The entrypoint of `oc-build-deploy-dind` is https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy.sh which will:
1.  checkout the git repository 
2. call [build-deploy-docker-compose.sh](https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh) which will itself:
3. figure out from the docker-compose.yml what type of services (in the future: which helm charts should be used, for the POC maybe we could commit the helm charts directly in the git repo, in an actual usable system we would like to not bother the lagoon users with that, all they should do is just define `lagoon.type: mariadb` and helm should figure out that it should use a helm chart for `mariadb`) (this happens currently in https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L35-L89)
4. Build the Docker Images for the service from docker-compose that define them (happens in https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L91-L161)
5. Create OpenShift objects (Services, Routes/Ingress, ConfigMaps) based on some given data within .lagoon.yml (happens in https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L174-L304)
6. Push the built images to the internal OpenShift Registry (https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L358-L363) 
7. Create more OpenShift Objects (Deployments, PVCs) based on the figured out services (happens in https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L365-L495)
8. Wait for the new pods actually be available (happens in https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L497-L539)
9. Run defined `post-rollout` tasks from .lagoon: https://github.com/amazeeio/lagoon/blob/master/images/oc-build-deploy-dind/build-deploy-docker-compose.sh#L552-L575

Now Helm could probably already do 5, 7 and 8. I'm not sure about the other ones. For the POC we could either leverage the existing bash script and just inject Helm at the places 5,7 and 8 (maybe also refactor that the step 6 happens before 5 and then helm just is called in one place in the whole script), or on the other side we could also teach helm about 1-9.
