### ISSUE TITLE
Variables defined in `.lagoon.env.$branch` are not available during build/post-rollout

### ISSUE THREAD

**Issue by ocean90** [uselagoon/lagoon#574]
**Describe the bug**
I have defined an env variable in `.lagoon.env.master` and trying to use it in a post-rollout task. But the variable does not exist.

**To Reproduce**
1. Create `.lagoon.env.master`
2. Add `MY_VAR=foobar`
3. Add `env | grep MY_VAR` to the rollout tasks
4. See missing `MY_VAR` in the `env` output

**Expected behavior**
`env | grep MY_VAR` returns `MY_VAR=foobar`

**Additional context**
The env variables should be set by [dotenv.sh](https://github.com/amazeeio/lagoon/blob/ecc4db879012eb8ebf20fc7de1449b2d7133f124/images/commons/lagoon/entrypoints/50-dotenv.sh#L30-L32). But based on the logs I think `$LAGOON_GIT_BRANCH` and `$LAGOON_GIT_SAFE_BRANCH` are not set at this point?

<img width="388" alt="missing-variables" src="https://user-images.githubusercontent.com/617637/44143819-731df7b2-a085-11e8-89f5-b4377403a0b6.png">

**Comment by rocketeerbkw** [comment]
You can get around this issue for the moment by sourcing `.bashrc` as part of the task, e.g.

```
  post-rollout:
    - run:
        name: Clear caches
        command: source /home/.bashrc && /app/clear_caches.sh
        service: cli
```

**Comment by bomoko** [comment]
Despite there being a workaround, this still seems to be an issue.

**Comment by tobybellwood** [comment]
Can be considered as part of the environment variable rollup work to happen in build-deploy-tool. These env vars can be included in the configmap then, which would make them available to exec'd environments.

**Comment by rocketeerbkw** [comment]
Also want to mention that another workaround is to explicitly use bash for the task:

```
  post-rollout:
    - run:
        name: Clear caches
        command: /app/clear_caches.sh
        service: cli
        shell: bash
```
