### ISSUE TITLE
Better management for Xdebug

### ISSUE THREAD

**Issue by Leksat** [uselagoon/lagoon#676]
## Current state

We have `XDEBUG_ENABLE` boolean in `docker-compose.yml`. Once it is enabled:
- all cli PHP processes can be debugged
- some frontend requests can be debugged
  - according to [Xdebug rules](https://xdebug.org/docs/remote), there should be `XDEBUG_SESSION` cookie or `XDEBUG_SESSION_START` query parameter in the request
  - usually developers use the Xdebug Helper browser extension to be able to quickly toggle the debugger with a hotkey

## Current issue

While it's easy to turn on/off the Xdebug for frontend requests, all cli PHP processes go through the debugger. And it's not so fast to edit `docker-compose.yml` and restart the containers. As a result, Drush commands execute much slower than usual.

## Proposed solution

- Introduce `XDEBUG_ENABLE_CLI` and `XDEBUG_ENABLE_FRONTEND` (`_FPM`?)
- Deprecate `XDEBUG_ENABLE` (or just leave it as it is?)

I think it should not be hard for me to prepare a PR if the idea sounds interesting.

**Comment by Leksat** [comment]
Ha! I was completely wrong. There is no need to change the current setup:
- `XDEBUG_ENABLE` sits under `x-environment.&default-environment` just to make it available from all containers at once
- it is possible to add `XDEBUG_ENABLE` per service
- if `XDEBUG_ENABLE` is set per service, it is possible to use `docker-compose.override.yml` like this:
```
version: '2.3'

services:
  php:
    environment:
      XDEBUG_ENABLE: "true"
  cli:
    environment:
      XDEBUG_ENABLE: "true"
```
(just checked this, works like a charm)

@Schnitzel what is the best place to put this information?

Maybe I can just update this comment? https://github.com/amazeeio/drupal-example/blob/f9ea2b521d264249f1373172c403bec881f76dd6/docker-compose.yml#L20

Or better to put it to lagoon.readthedocs.io?

**Comment by Leksat** [comment]
So the recipe is:
- Exclude `docker-compose.override.yml` from Git
- Create `docker-compose.override.yml` locally. Example:
```yaml
version: '2.3'

services:
  php:
    environment:
      XDEBUG_ENABLE: 'true' # the value does not matter
  cli:
    environment:
      XDEBUG_ENABLE: null # means the environment variable will not exist
```
