### ISSUE TITLE
allow definition of persistent storage in .lagoon.yml

### ISSUE THREAD

**Issue by Schnitzel** [uselagoon/lagoon#91]
example:

```
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile.nginx
    labels:
      lagoon.type: nginx-php
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.name: nginx-php
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - builder
    expose:
      - "8080"
    environment:
      - AMAZEEIO_URL=drupal.docker.amazee.io
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php
      lagoon.persistent: /app/docroot/sites/default/files/
      lagoon.name: nginx-php
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - builder
```
