### ISSUE TITLE
Routes definition with tls-acme parsing problem - DNS-1123 subdomain must consist of lower case alphanumeric characters...

### ISSUE THREAD

**Issue by twerthmueller** [uselagoon/lagoon#915]
We had a problem with the deployment when we had defined the tls-acme value in .lagoon.yml:

`Error from server (Invalid): Route "vse.ch:\n  tls-acme: 'false'" is invalid: [metadata.name: Invalid value: "vse.ch:\n  tls-acme: 'false'": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), spec.host: Invalid value: "vse.ch:\n  tls-acme: 'false'": host must conform to DNS 952 subdomain conventions]`

We have added the config as described here: https://lagoon.readthedocs.io/en/latest/using_lagoon/lagoon_yml/

![strom ch 2019-02-26 14-37-20](https://user-images.githubusercontent.com/6920143/53416613-2948d600-39d4-11e9-816d-f0fc825b4fc5.png)

Looks like that there is a problem with the line break.

**Comment by marji** [comment]
I can confirm I'm also affected by this issue. I tried all different kind of spacing in the `routes` section, I used yamlling on the `.lagoon.yml` file, but I keep getting this error.

**Comment by Schnitzel** [comment]
mhh unfortunately I cannot reproduce this:

```
oc-build-deploy-dind:/oc-build-deploy/git$ cat test.yml
site:
  environments:
    master:
      routes:
        - varnish:
          - "strom.ch"
          - "www.strom.ch"
          - "vse.ch":
              tls-acme: 'false'
          - "www.vse.ch"
          - "poweron.ch"

oc-build-deploy-dind:/oc-build-deploy/git$ cat test.yml | shyaml keys site.environments.master.routes.0.varnish.2 | sed 's/\./\\./g'
vse\.ch
```

**Comment by Schnitzel** [comment]
@marji @twerthmueller 
can you paste the yaml you tried with in here?

**Comment by marji** [comment]
@Schnitzel Here is my config (I just redacted the domain names)
```
polysite1:
  environments:
    master:
      routes:
        - nginx:
          - "www.polysite1.org.au":
              tls-acme: 'false'
          - "polysite1.org.au":
              tls-acme: 'false'
          - polysite1-prod.org.net
```
